/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobId = IDL.Nat;
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'converting' : IDL.Null,
});
export const Time = IDL.Int;
export const ConversionJob = IDL.Record({
  'id' : JobId,
  'status' : Status,
  'createdAt' : Time,
  'filename' : IDL.Text,
  'progress' : IDL.Nat,
  'targetFormat' : IDL.Text,
  'sourceFormat' : IDL.Text,
});

export const idlService = IDL.Service({
  'createJob' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [JobId], []),
  'getJob' : IDL.Func([JobId], [IDL.Opt(ConversionJob)], ['query']),
  'getRecentJobs' : IDL.Func([IDL.Nat], [IDL.Vec(ConversionJob)], ['query']),
  'updateProgress' : IDL.Func([JobId, Status, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobId = IDL.Nat;
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'converting' : IDL.Null,
  });
  const Time = IDL.Int;
  const ConversionJob = IDL.Record({
    'id' : JobId,
    'status' : Status,
    'createdAt' : Time,
    'filename' : IDL.Text,
    'progress' : IDL.Nat,
    'targetFormat' : IDL.Text,
    'sourceFormat' : IDL.Text,
  });
  
  return IDL.Service({
    'createJob' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [JobId], []),
    'getJob' : IDL.Func([JobId], [IDL.Opt(ConversionJob)], ['query']),
    'getRecentJobs' : IDL.Func([IDL.Nat], [IDL.Vec(ConversionJob)], ['query']),
    'updateProgress' : IDL.Func([JobId, Status, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };